# Multistage dockerfile for nodeapp backend
# Stage 1: Build
FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# Stage 2: Production
FROM node:20-slim

WORKDIR /app

# Copy only necessary files from the builder
COPY --from=builder /app /app

EXPOSE 5000

CMD ["npm", "start"]
